name: App Python CI Pipeline

on:
  push:
    branches:
      - master
    paths:
      - app_python/**
  pull_request:
    branches:
      - master
    paths:
      - app_python/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_python

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
            context: app_python
            push: true
            tags: absorian/s25-devops-msk-time:latest
